import { Plan, Farm, Plot, Crop, Delivery, Customer, FarmUpdate, Lead, SystemConfig } from './types';

export const INITIAL_PLANS: Plan[] = [
  {
    id: 'family',
    name: "My Family's Farm",
    price: 10000,
    billingPeriod: 'month',
    monthlyEquivalent: 10000,
    tagline: 'Everyday Freshness',
    description: "Premium managed farming for your family's everyday produce.",
    targetAudience: 'Families who want premium, fresh and traceable farm produce without managing a farm themselves.',
    features: [
      'Family-focused vegetable production (approx. 25-30 kg/month)',
      'Seasonal crop selection guided by agronomy calendar',
      'Regular fresh produce delivery directly to your home',
      'Farm photos and video updates every week',
      'Bi-weekly crop progress updates on your portal',
      'Rigorous multi-stage quality checking before dispatch',
      'Direct WhatsApp advisor support',
      'Flexible subscription management',
    ],
    ctaLabel: 'Start My Farm',
  },
  {
    id: 'dedicated',
    name: 'My Dedicated Farm',
    price: 20000,
    billingPeriod: 'month',
    monthlyEquivalent: 20000,
    tagline: 'Tailored Cultivation',
    badge: 'Most Popular',
    description: 'Your dedicated farming space with customised crop planning.',
    targetAudience: 'Families who want a dedicated farming space and greater control over what is grown.',
    features: [
      'Dedicated numbered plot exclusively allocated to your family',
      'Customer-selected crops tailored to your family kitchen',
      'Custom seasonal crop planning with lead agronomist',
      'Regular farm video walkthroughs & high-res photo updates',
      'End-to-end harvest tracking with live countdowns',
      'Priority scheduled delivery in temperature-controlled boxes',
      'Dedicated personal customer support concierge',
      'Open invitation for scheduled farm visits with your family',
    ],
    ctaLabel: 'Create My Dedicated Farm',
  },
  {
    id: 'private',
    name: 'My Private Farm',
    price: 700000,
    billingPeriod: 'year',
    monthlyEquivalent: 58333,
    tagline: 'The Ultimate Managed Estate',
    description: 'A fully managed private farming experience for your family.',
    targetAudience: 'High-net-worth customers who want a fully managed private farming experience.',
    features: [
      'Private dedicated farm estate area (up to 1/2 acre allocated)',
      'Complete end-to-end estate management by senior agronomists',
      'Custom artisan & heirloom crop planning for private households',
      'Premium vegetable, culinary herb & microgreen production',
      'Live Farm Monitoring camera stream accessible anytime',
      'Detailed monthly soil health, water lab & farming reports',
      'Bespoke harvest schedule aligned with your chef or cook',
      'Signature wooden crate packaging & white-glove doorstep delivery',
      'Dedicated personal Farm Manager assigned exclusively',
      'Private farm visits with family picnics & guided harvesting',
      'Custom cultivation requests & bespoke seasonal trials',
    ],
    ctaLabel: 'Talk to a Farm Manager',
  },
];

export const INITIAL_FARMS: Farm[] = [
  {
    id: 'farm-anekal',
    name: 'Anekal Valley Agro Estate',
    code: 'FARM-BLR-01',
    location: 'Anekal Foothills, South Bengaluru',
    state: 'Karnataka',
    totalAreaAcres: 24,
    availableAreaAcres: 6.5,
    soilType: 'Red Sandy Loam enriched with aged vermicompost',
    soilPh: 6.8,
    waterSource: 'Rainwater harvesting lake & deep aquifer borewell (Filtered)',
    waterTds: 185,
    climateZone: 'Deccan Plateau Semi-Arid Subtropical',
    images: [
      'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1592417817098-8f3d6ef23992?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=1200&q=80',
    ],
    agronomistName: 'Dr. Srinivas Murthy',
    agronomistContact: '+91 98450 44210',
    establishedYear: 2021,
  },
  {
    id: 'farm-baramati',
    name: 'Sahyadri Terraces Farm',
    code: 'FARM-PNE-02',
    location: 'Baramati Ridge, Western Ghats Foothills',
    state: 'Maharashtra',
    totalAreaAcres: 35,
    availableAreaAcres: 9.0,
    soilType: 'Black Silt Loam with organic mulch beds',
    soilPh: 7.1,
    waterSource: 'Drip-fed mountain gravity canal with sand filtration',
    waterTds: 210,
    climateZone: 'Western Ghats Leeward Temperate',
    images: [
      'https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=1200&q=80',
    ],
    agronomistName: 'Kavita Deshmukh, M.Sc. Agronomy',
    agronomistContact: '+91 98230 77142',
    establishedYear: 2022,
  },
  {
    id: 'farm-sohna',
    name: 'Aravalli Greens Sanctuary',
    code: 'FARM-NCR-03',
    location: 'Sohna Rural Corridor, Gurugram Outskirts',
    state: 'Haryana / NCR',
    totalAreaAcres: 18,
    availableAreaAcres: 3.2,
    soilType: 'Alluvial Loamy Clay with biochar conditioning',
    soilPh: 7.3,
    waterSource: 'Sub-surface aquifer with double RO mineral filtration',
    waterTds: 195,
    climateZone: 'North Indian Indo-Gangetic Plains',
    images: [
      'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=1200&q=80',
    ],
    agronomistName: 'Harinder Singh Brar',
    agronomistContact: '+91 98110 59281',
    establishedYear: 2023,
  },
];

export const INITIAL_PLOTS: Plot[] = [
  {
    id: 'plot-14',
    plotNumber: 'Plot B-14',
    farmId: 'farm-anekal',
    farmName: 'Anekal Valley Agro Estate',
    sizeSqFt: 2400,
    status: 'growing',
    assignedCustomerId: 'cust-rahul-01',
    assignedCustomerName: 'Rahul Verma',
    assignedCrops: ['Heirloom Tomato', 'Early Nantes Carrot', 'English Cucumber', 'Green Bell Peppers'],
    soilQualityIndex: 'Excellent (SQI 94/100)',
    sunlightHours: 7.5,
    irrigationType: 'Precision sub-surface micro drip',
  },
  {
    id: 'plot-01-private',
    plotNumber: 'Private Estate P-01',
    farmId: 'farm-sohna',
    farmName: 'Aravalli Greens Sanctuary',
    sizeSqFt: 18000,
    status: 'growing',
    assignedCustomerId: 'cust-vikram-hni',
    assignedCustomerName: 'Vikram Singhania',
    assignedCrops: ['San Marzano Tomatoes', 'Rainbow Carrots', 'Baby Spinach', 'Zucchini', 'French Green Beans', 'Culinary Herbs'],
    soilQualityIndex: 'Master Reserve Grade (SQI 98/100)',
    sunlightHours: 8.2,
    irrigationType: 'Smart automated solar-drip with soil moisture feedback',
  },
  {
    id: 'plot-09',
    plotNumber: 'Plot A-09',
    farmId: 'farm-baramati',
    farmName: 'Sahyadri Terraces Farm',
    sizeSqFt: 1500,
    status: 'harvest_ready',
    assignedCustomerId: 'cust-meera-02',
    assignedCustomerName: 'Meera Patel',
    assignedCrops: ['Cauliflower Snowball', 'Bottle Gourd', 'Green Peas', 'Brinjal'],
    soilQualityIndex: 'High Fertility (SQI 91/100)',
    sunlightHours: 7.8,
    irrigationType: 'Micro-sprinkler & drip',
  },
  {
    id: 'plot-22',
    plotNumber: 'Plot C-22',
    farmId: 'farm-anekal',
    farmName: 'Anekal Valley Agro Estate',
    sizeSqFt: 2000,
    status: 'available',
    assignedCrops: [],
    soilQualityIndex: 'Optimal Resting & Compost Prepped (SQI 93/100)',
    sunlightHours: 7.6,
    irrigationType: 'Precision drip manifold ready',
  },
];

export const INITIAL_CROPS: Crop[] = [
  {
    id: 'crop-tom-1',
    name: 'Tomato',
    variety: 'Heirloom San Marzano & Roma',
    plotId: 'plot-14',
    farmId: 'farm-anekal',
    customerId: 'cust-rahul-01',
    sowingDate: '2026-08-15',
    expectedHarvestDate: '2026-10-25',
    currentStage: 'growing',
    progressPercent: 78,
    expectedYieldKg: 14,
    notes: 'Vigorous indeterminate vine growth. Fruit setting is abundant and deep green. Trellised with natural jute twines.',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
    healthStatus: 'optimal',
  },
  {
    id: 'crop-car-1',
    name: 'Carrot',
    variety: 'Early Nantes Sweet Crunchy',
    plotId: 'plot-14',
    farmId: 'farm-anekal',
    customerId: 'cust-rahul-01',
    sowingDate: '2026-08-28',
    expectedHarvestDate: '2026-11-08',
    currentStage: 'growing',
    progressPercent: 58,
    expectedYieldKg: 10,
    notes: 'Root swelling underway in raised friable sand beds. Foliage shows zero leaf curl or blight. Regular neem oil foliar misting applied.',
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5c317?auto=format&fit=crop&w=800&q=80',
    healthStatus: 'optimal',
  },
  {
    id: 'crop-cuc-1',
    name: 'Cucumber',
    variety: 'English Seedless Crisp',
    plotId: 'plot-14',
    farmId: 'farm-anekal',
    customerId: 'cust-rahul-01',
    sowingDate: '2026-08-05',
    expectedHarvestDate: '2026-10-10',
    currentStage: 'harvest',
    progressPercent: 95,
    expectedYieldKg: 12,
    actualYieldKg: 11.5,
    notes: 'First harvest picking commencing this morning. Fruit length averages 20-22cm with thin skin and zero bitterness.',
    imageUrl: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&w=800&q=80',
    healthStatus: 'optimal',
  },
  {
    id: 'crop-cap-1',
    name: 'Capsicum',
    variety: 'California Wonder Bell Pepper',
    plotId: 'plot-14',
    farmId: 'farm-anekal',
    customerId: 'cust-rahul-01',
    sowingDate: '2026-08-20',
    expectedHarvestDate: '2026-10-30',
    currentStage: 'flowering',
    progressPercent: 68,
    expectedYieldKg: 8,
    notes: 'Heavy flowering stage under 40% shade net. Bio-inoculants promoting thick wall development for crunch.',
    imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
    healthStatus: 'optimal',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-rahul-01',
    fullName: 'Rahul Verma',
    email: 'rahul.verma@example.com',
    phone: '+91 98450 11234',
    whatsapp: '+91 98450 11234',
    city: 'Bengaluru',
    address: 'Apartment 702, Prestige Elm Park, Whitefield, Bengaluru - 560066',
    familySize: 4,
    planId: 'dedicated',
    planName: 'My Dedicated Farm',
    subscriptionStatus: 'active',
    farmId: 'farm-anekal',
    farmName: 'Anekal Valley Agro Estate',
    plotId: 'plot-14',
    plotNumber: 'Plot B-14',
    selectedCrops: ['Heirloom Tomato', 'Early Nantes Carrot', 'English Cucumber', 'Green Bell Peppers'],
    subscriptionStartDate: '2026-06-01',
    renewalDate: '2026-11-01',
    monthlyAmount: 20000,
    totalPaid: 100000,
    dietaryPreferences: ['Low bitterness cucumbers', 'Salad tomatoes', 'Fresh sweet carrots'],
    dedicatedFarmManager: 'Dr. Srinivas Murthy',
    hasLiveCameraAccess: true,
  },
  {
    id: 'cust-vikram-hni',
    fullName: 'Vikram Singhania',
    email: 'vikram.singhania@singhaniagroup.com',
    phone: '+91 98110 99887',
    whatsapp: '+91 98110 99887',
    city: 'New Delhi / Gurugram',
    address: 'The Magnolias, Golf Course Road, Sector 42, Gurugram - 122002',
    familySize: 5,
    planId: 'private',
    planName: 'My Private Farm',
    subscriptionStatus: 'active',
    farmId: 'farm-sohna',
    farmName: 'Aravalli Greens Sanctuary',
    plotId: 'plot-01-private',
    plotNumber: 'Private Estate P-01',
    selectedCrops: ['San Marzano Tomatoes', 'Rainbow Carrots', 'Baby Spinach', 'Zucchini', 'French Green Beans', 'Culinary Herbs'],
    subscriptionStartDate: '2026-03-01',
    renewalDate: '2027-03-01',
    monthlyAmount: 58333,
    totalPaid: 700000,
    dietaryPreferences: ['Artisan salad greens', 'Estate harvested soup vegetables', 'Zero synthetic wash'],
    dedicatedFarmManager: 'Harinder Singh Brar',
    hasLiveCameraAccess: true,
  },
  {
    id: 'cust-meera-02',
    fullName: 'Meera Patel',
    email: 'meera.patel@outlook.com',
    phone: '+91 98220 54321',
    whatsapp: '+91 98220 54321',
    city: 'Pune',
    address: 'Rowhouse 12, Nyati Windchimes, Undri, Pune - 411060',
    familySize: 3,
    planId: 'family',
    planName: "My Family's Farm",
    subscriptionStatus: 'active',
    farmId: 'farm-baramati',
    farmName: 'Sahyadri Terraces Farm',
    plotId: 'plot-09',
    plotNumber: 'Plot A-09',
    selectedCrops: ['Cauliflower Snowball', 'Bottle Gourd', 'Green Peas', 'Brinjal'],
    subscriptionStartDate: '2026-07-15',
    renewalDate: '2026-10-15',
    monthlyAmount: 10000,
    totalPaid: 30000,
    dietaryPreferences: ['Indian regional cooking staples', 'Tender gourds'],
    dedicatedFarmManager: 'Kavita Deshmukh',
    hasLiveCameraAccess: false,
  },
];

export const INITIAL_DELIVERIES: Delivery[] = [
  {
    id: 'del-01',
    deliveryCode: 'FTF-DEL-2610-09',
    customerId: 'cust-rahul-01',
    customerName: 'Rahul Verma',
    farmId: 'farm-anekal',
    plotId: 'plot-14',
    scheduledDate: '2026-10-09',
    status: 'dispatched',
    items: [
      { cropName: 'English Cucumber', variety: 'Seedless Crisp', quantityKg: 3.5, qualityGrade: 'A+' },
      { cropName: 'Heirloom Tomato', variety: 'Early Harvest Vine', quantityKg: 2.8, qualityGrade: 'A+' },
      { cropName: 'Baby Spinach', variety: 'All Green Tender', quantityKg: 1.2, qualityGrade: 'A' },
      { cropName: 'Green Bell Peppers', variety: 'California Wonder', quantityKg: 1.8, qualityGrade: 'A+' },
    ],
    totalWeightKg: 9.3,
    temperatureAtDispatch: '12.4°C in insulated chilled pack',
    qcInspector: 'R. K. Sharma (Chief Quality Agronomist)',
    trackingNotes: 'Dispatched from Anekal Hub at 06:15 AM via climate-controlled EV. Out for doorstep delivery.',
  },
  {
    id: 'del-02',
    deliveryCode: 'FTF-DEL-2610-02',
    customerId: 'cust-rahul-01',
    customerName: 'Rahul Verma',
    farmId: 'farm-anekal',
    plotId: 'plot-14',
    scheduledDate: '2026-10-02',
    actualDeliveryDate: '2026-10-02',
    status: 'delivered',
    items: [
      { cropName: 'Carrot', variety: 'Baby Nantes', quantityKg: 2.5, qualityGrade: 'A+' },
      { cropName: 'Tomato', variety: 'Roma Vine', quantityKg: 3.2, qualityGrade: 'A+' },
      { cropName: 'Bottle Gourd', variety: 'Tender Green', quantityKg: 2.0, qualityGrade: 'A' },
    ],
    totalWeightKg: 7.7,
    temperatureAtDispatch: '13.1°C',
    qcInspector: 'R. K. Sharma',
    trackingNotes: 'Delivered at 09:30 AM. Signed by customer.',
  },
];

export const INITIAL_UPDATES: FarmUpdate[] = [
  {
    id: 'upd-1',
    farmId: 'farm-anekal',
    plotId: 'plot-14',
    customerId: 'cust-rahul-01',
    date: '2026-10-06',
    title: 'Morning Dew Inspection & Trellis Reinforcement',
    content: 'Dr. Murthy completed weekly shoot inspection on Plot B-14. Soil moisture is optimal at 38% field capacity. Trellis strings for the heirloom tomatoes were tightened to support heavy cluster swelling. First cucumber batch harvested cleanly with sanitized shears.',
    author: 'Dr. Srinivas Murthy',
    authorRole: 'Lead Agronomist, Anekal Estate',
    category: 'agronomy',
    mediaUrls: [
      'https://images.unsplash.com/photo-1592417817098-8f3d6ef23992?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'upd-2',
    farmId: 'farm-anekal',
    plotId: 'plot-14',
    customerId: 'cust-rahul-01',
    date: '2026-10-02',
    title: 'Biological Pest Shield & Neem Cake Compost Dressing',
    content: 'Applied our scheduled bio-control dressing: fermented neem seed kernel extract and Trichoderma bio-inoculant. No synthetic systemic chemicals are ever introduced into your family rootzone.',
    author: 'Sunil Gowda',
    authorRole: 'Senior Farm Cultivator',
    category: 'agronomy',
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-01',
    fullName: 'Ananya Deshpande',
    phone: '+91 98201 44552',
    whatsapp: '+91 98201 44552',
    city: 'Mumbai',
    familySize: '3–4',
    interestedPlan: 'dedicated',
    monthlyBudget: '₹20,000 / month',
    selectedVegetables: ['Tomato', 'Cucumber', 'Capsicum', 'Beans'],
    primaryPriority: 'Traceable sourcing & family supply',
    createdAt: '2026-10-06T10:30:00Z',
    status: 'new',
  },
];

export const SYSTEM_CONFIG: SystemConfig = {
  whatsappNumber: '+91 98450 12345',
  supportPhone: '+91 (080) 4120-7788',
  supportEmail: 'care@farmtofamily.in',
  headquartersAddress: 'Farm-to-Family Agro Labs, 4th Floor, Estate Hub, 100 Ft Road, Indiranagar, Bengaluru 560038',
  plans: INITIAL_PLANS,
  vegetableCatalog: [
    {
      id: 'veg-carrot',
      name: 'Carrot',
      category: 'root',
      season: 'all-year',
      typicalDaysToHarvest: 75,
      benefits: 'Grown in aerated sand-loam beds. Rich in beta-carotene and natural root crunch.',
      image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5c317?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'veg-cabbage',
      name: 'Cabbage',
      category: 'leafy',
      season: 'winter',
      typicalDaysToHarvest: 65,
      benefits: 'Tight heads with zero synthetic wash. High dietary fiber and crisp layers.',
      image: 'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'veg-cauliflower',
      name: 'Cauliflower',
      category: 'seasonal',
      season: 'winter',
      typicalDaysToHarvest: 70,
      benefits: 'Blanched under natural leaf tucking to retain porcelain white florets.',
      image: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'veg-capsicum',
      name: 'Capsicum (Bell Pepper)',
      category: 'fruit',
      season: 'all-year',
      typicalDaysToHarvest: 80,
      benefits: 'Thick-walled green & yellow peppers with superior shelf life and snap.',
      image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'veg-bottle-gourd',
      name: 'Bottle Gourd (Lauki)',
      category: 'creeper',
      season: 'summer',
      typicalDaysToHarvest: 55,
      benefits: 'Light green, tender, seed-free center. Perfect for morning juices and gentle curries.',
      image: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'veg-chilli',
      name: 'Green Chilli',
      category: 'fruit',
      season: 'all-year',
      typicalDaysToHarvest: 60,
      benefits: 'Aromatic, sun-ripened chillies with balanced capsicum kick and clean skin.',
      image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'veg-peas',
      name: 'Green Peas',
      category: 'seasonal',
      season: 'winter',
      typicalDaysToHarvest: 65,
      benefits: 'Plump sweet pods packed with morning sweetness, picked in peak frost.',
      image: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'veg-brinjal',
      name: 'Brinjal (Eggplant)',
      category: 'fruit',
      season: 'all-year',
      typicalDaysToHarvest: 70,
      benefits: 'Tender purple varieties with buttery flesh when roasted or sautéed.',
      image: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'veg-cucumber',
      name: 'Cucumber',
      category: 'creeper',
      season: 'all-year',
      typicalDaysToHarvest: 50,
      benefits: 'Crisp, hydrative, grown on vertical trellis lines with zero ground grit.',
      image: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'veg-tomato',
      name: 'Tomato',
      category: 'fruit',
      season: 'all-year',
      typicalDaysToHarvest: 75,
      benefits: 'Sun-warmed heirloom varieties with real tomato aroma and sweet-tangy balance.',
      image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'veg-beans',
      name: 'French Beans',
      category: 'creeper',
      season: 'all-year',
      typicalDaysToHarvest: 55,
      benefits: 'Stringless, tender, slender pods snapped fresh on harvest mornings.',
      image: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=600&q=80',
    },
    {
      id: 'veg-seasonal',
      name: 'Seasonal Farm Specials',
      category: 'seasonal',
      season: 'winter',
      typicalDaysToHarvest: 60,
      benefits: 'Agronomist-curated seasonal vegetables, leafy greens and traditional roots.',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    },
  ],
};
